insert into customer (email, fname, lname) values ('alice@wonderland','Alice','Wonderland');
insert into customer (email, fname, lname) values ('bob@marley','Bob','Marley');
insert into customer (email, fname, lname) values ('charlie@chad','Charlie','Chad');
Insert into customer (email, fname, lname) values ('dan@brown','Dan','Brown');
insert into wallet values (1,1);
insert into wallet values (2,2);
insert into wallet values (3,3);
-- insert into wallet values (4,4);
insert into account (account_number, balance, account_holder_user_id, wallet_holder_wallet_id) values (1000, 1000, 1, 1 );
insert into account (account_number, balance, account_holder_user_id, wallet_holder_wallet_id) values (2000, 2000, 2, 2 );
insert into account (account_number, balance, account_holder_user_id, wallet_holder_wallet_id) values (3000, 3000, 3, 3 );
-- insert into account (account_number, balance, account_holder_user_id, wallet_holder_wallet_id) values (4000, 4000, 4, 4 );
